apiVersion: v1
kind: Pod
metadata:
  name: mlflow-server
spec:
  containers:
  - name: mlflow
    image: wjayesh/mlflow-tracking-server
    command: ["mlflow server"]
#larribas/mlflow:1.9.1
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: /data 
      name: hostpath

  volumes:
    - name: hostpath
      persistentVolumeClaim:
        claimName: mlflow-pvc-volume
